on:
  push:
    branches:
      - master





jobs:
  build:
    runs-on: ubuntu-latest


    steps:
      - uses: actions/checkout@v3


      - name: "login to dockerhub"
        run: docker login --username ${{secrets.DOCKER_USERNAME}} --password ${{ secrets.DOCKER_TOKEN }}
      
      - name: "buiding image"
<<<<<<< HEAD
        run: docker build -t ${{secrets.DOCKER_USERNAME}}/yasminenaser2023040408 .

      - name: "pushing to dockerhub" 
        run: docker push ${{ secrets.DOCKER_USERNAME }}/yasminenaser2023040408
=======
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/yasminenaser2023040408 .

      - name: "pushing to dockerhub" 
        run: docker push ${{secrets.DOCKER_USERNAME}}/yasminenaser2023040408
>>>>>>> bef46a0ee1f653572035981cff12223876bee54a
 

